// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {instance} from '../models';
import {sync} from '../models';

export function AddServer(arg1:string):Promise<void>;

export function ApplyUpdates(arg1:string,arg2:Array<string>):Promise<void>;

export function CheckUpdates(arg1:string):Promise<Record<string, any>>;

export function DiscoverAllLaunchers():Promise<Array<string>>;

export function GetConfig():Promise<config.Config>;

export function GetServers():Promise<Array<instance.ScannedInstance>>;

export function OpenInstanceDir(arg1:string):Promise<void>;

export function PreviewServer(arg1:string):Promise<sync.InfoResponse>;

export function RefreshServerInfo(arg1:string):Promise<void>;

export function RemoveServer(arg1:string):Promise<void>;

export function RunServer(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectInstancesDir():Promise<string>;

export function UpdateServerURL(arg1:string,arg2:string):Promise<void>;
