// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {instance} from '../models';

export function AddServer(arg1:string):Promise<void>;

export function ApplyUpdates(arg1:string,arg2:Array<string>):Promise<void>;

export function CheckUpdates(arg1:string):Promise<Record<string, any>>;

export function DiscoverAllLaunchers():Promise<Array<string>>;

export function GetConfig():Promise<config.Config>;

export function GetServers():Promise<Array<instance.ScannedInstance>>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectInstancesDir():Promise<string>;
