// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function ApplyUpdates(arg1, arg2) {
  return window['go']['main']['App']['ApplyUpdates'](arg1, arg2);
}

export function CheckUpdates(arg1) {
  return window['go']['main']['App']['CheckUpdates'](arg1);
}

export function DiscoverAllLaunchers() {
  return window['go']['main']['App']['DiscoverAllLaunchers']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectInstancesDir() {
  return window['go']['main']['App']['SelectInstancesDir']();
}
