// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function ApplyUpdates(arg1, arg2) {
  return window['go']['main']['App']['ApplyUpdates'](arg1, arg2);
}

export function CancelUpdate() {
  return window['go']['main']['App']['CancelUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckUpdates(arg1) {
  return window['go']['main']['App']['CheckUpdates'](arg1);
}

export function DiscoverAllLaunchers() {
  return window['go']['main']['App']['DiscoverAllLaunchers']();
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasPendingUpdate() {
  return window['go']['main']['App']['HasPendingUpdate']();
}

export function IsOperationRunning() {
  return window['go']['main']['App']['IsOperationRunning']();
}

export function OpenInstanceDir(arg1) {
  return window['go']['main']['App']['OpenInstanceDir'](arg1);
}

export function PreviewServer(arg1) {
  return window['go']['main']['App']['PreviewServer'](arg1);
}

export function RefreshServerInfo(arg1) {
  return window['go']['main']['App']['RefreshServerInfo'](arg1);
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RunManualCheck() {
  return window['go']['main']['App']['RunManualCheck']();
}

export function RunServer(arg1) {
  return window['go']['main']['App']['RunServer'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectInstancesDir() {
  return window['go']['main']['App']['SelectInstancesDir']();
}

export function UpdateServerURL(arg1, arg2) {
  return window['go']['main']['App']['UpdateServerURL'](arg1, arg2);
}
